import { inter } from './fonts';
import './global.css';
import RootProvider from './provider';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="dark" lang="en">
      <body className={`${inter.className}`}>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
